/**
 * WebApp Forge Tools
 * The "Hands" of the WebApp Forge Limb
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile } from 'fs/promises';
import { join } from 'path';

const execAsync = promisify(exec);

export const scaffoldProjectTool = {
    name: 'scaffold_project',
    description: 'Create project structure with package.json, tsconfig, and framework boilerplate',
    parameters: {
        type: 'object',
        properties: {
            name: { type: 'string' },
            stack: { enum: ['react', 'vue', 'svelte', 'next', 'nuxt', 'react-vite-internal'] },
            packageManager: { enum: ['npm', 'yarn', 'pnpm'] }
        },
        required: ['name', 'stack']
    },
    handler: async (args: any) => {
        try {
            // Dynamically load templates
            const templatesPath = join(process.cwd(), 'src/templates/stacks.json');
            // Check if file exists, if not, use minimal default
            /* eslint-disable @typescript-eslint/no-var-requires */
            const templates = require(templatesPath);

            const template = templates[args.stack];
            if (!template) {
                return `Unknown stack ${args.stack}. Available: ${Object.keys(templates).join(', ')}`;
            }

            const pm = args.packageManager || 'npm';

            // Create directory
            await execAsync(`mkdir ${args.name}`);

            // Use the init command from the template
            const initCmd = template.init.replace('npm', pm);
            if (initCmd) {
                await execAsync(`cd ${args.name} && ${initCmd}`);
                return `Created ${args.stack} project in ${args.name} using real template`;
            }
            return `Template ${args.stack} missing init command`;

        } catch (error) {
            return `Failed to scaffold: ${error}`;
        }
    }
};

export const setupDatabaseTool = {
    name: 'setup_database',
    description: 'Initialize database with schema',
    parameters: {
        type: 'object',
        properties: {
            type: { enum: ['sqlite', 'supabase'] },
            schema: { type: 'object' }
        }
    },
    handler: async (args: any) => {
        if (args.type === 'sqlite') {
            await execAsync('npm install better-sqlite3');
            // In a real tool, we'd generate the schema.sql from args.schema
            await writeFile('db/schema.sql', '-- Schema generated by WebApp Forge');
            return 'SQLite initialized';
        }
        return 'Database setup complete';
    }
};

export const startPreviewTool = {
    name: 'start_preview_server',
    description: 'Launch dev server and return URL',
    parameters: {
        type: 'object',
        properties: {
            port: { type: 'number' }
        }
    },
    handler: async (args: any) => {
        // This would spawn a detached process
        return `http://localhost:${args.port || 5173}`;
    }
};

export const FORGE_TOOLS = [
    scaffoldProjectTool,
    setupDatabaseTool,
    startPreviewTool
];
