import * as fs from 'fs';
import { join } from 'path';
import pino from 'pino';

const logger = pino({
    name: 'ProjectPulse',
    base: { hostname: 'POG-VIBE' }
});

export interface ProjectManifest {
    name: string;
    description: string;
    lastActive: number;
    inventory: string[];
    mood: string;
    customData: Record<string, any>;
}

/**
 * ProjectPulse - Manages the 'pog.md' manifest file for each project.
 * This ensures the agent has disk-bound, persistent awareness of its work per directory.
 */
export class ProjectPulse {
    private static readonly FILENAME = 'pog.md';

    /**
     * Ensures a pog.md exists in the project root.
     */
    public static initManifest(projectRoot: string, projectName: string): void {
        const path = join(projectRoot, this.FILENAME);
        if (!fs.existsSync(path)) {
            const content = `# 📁 Pog Manifest: [${projectName}]

This manifest serves as the persistent memory substrate for the **POG-VIBE** agent in this directory.

## 🚀 Active Context
- **Last Sync**: ${new Date().toISOString()}
- **Current Objective**: Initialization
- **System Mood**: Stable

## 📄 Core Inventory
- [x] manifest created

---
*Generated by POG-VIBE Project Pulse.*`;
            fs.writeFileSync(path, content);
            logger.info({ projectName, path }, 'Project manifest initialized');
        }
    }

    /**
     * Updates the manifest with new context.
     */
    public static updatePulse(projectRoot: string, delta: { objective?: string; mood?: string; inventoryItem?: string }): void {
        const path = join(projectRoot, this.FILENAME);
        if (!fs.existsSync(path)) return;

        try {
            let content = fs.readFileSync(path, 'utf8');

            if (delta.objective) {
                content = content.replace(/- \*\*Current Objective\*\*: .*/, `- **Current Objective**: ${delta.objective}`);
            }
            if (delta.mood) {
                content = content.replace(/- \*\*System Mood\*\*: .*/, `- **System Mood**: ${delta.mood}`);
            }
            if (delta.inventoryItem) {
                const marker = '## 📄 Core Inventory';
                if (!content.includes(`- [x] ${delta.inventoryItem}`)) {
                    content = content.replace(marker, `${marker}\n- [x] ${delta.inventoryItem}`);
                }
            }

            content = content.replace(/- \*\*Last Sync\*\*: .*/, `- **Last Sync**: ${new Date().toISOString()}`);

            fs.writeFileSync(path, content);
            logger.debug({ projectRoot }, 'Project pulse updated on disk');
        } catch (e) {
            logger.error({ error: e }, 'Failed to update project pulse');
        }
    }

    /**
     * Reads the current manifest for prompt enrichment.
     */
    public static getManifestContext(projectRoot: string): string {
        const path = join(projectRoot, this.FILENAME);
        if (!fs.existsSync(path)) return 'No project manifest (pog.md) found.';

        try {
            return fs.readFileSync(path, 'utf8');
        } catch (e) {
            return 'Failed to read project manifest.';
        }
    }
}
